services:
  frontend:
    build:
      context: ./FRONT-END
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./FRONT-END/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./api/.env
